---
title: "Terremotos y HTML Widgets"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: ["Twitter", "LinkedInd"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(dplyr)
library(leaflet)
library(crosstalk)
library(DT)
```

```{r data}
earthquakedata = read.csv("https://raw.githubusercontent.com/chzelada/ufm-dp-2022/main/FlexDashBoard/data/earthquakedata.csv", sep = ",")
```

# Static {data-icon=fa-chalkboard}

##

###

```{r}
earthquakedata %>% filter(yr == 1995) %>% datatable()
```

###

```{r}
earthquakedata %>% filter(yr == 1995) %>% leaflet() %>% addTiles() %>% 
  addMarkers(lng = ~lon, lat = ~lat, label = ~yr)
```

-------------------------------------------------------------------------------
# Dinamic {data-icon=fa-rocket}

```{r}
data_share = SharedData$new(earthquakedata %>% filter(yr > 2000))
```

### {data-width=100}

```{r}
filter_slider("mag", "Magnitud", data_share, step = 0.1, width = 250, column = 
    ~mag)
filter_select("yr", "Year", data_share, group = ~yr, multiple = FALSE)
```

##


###


```{r}
data_share %>% datatable()
```

###

```{r}
data_share %>% leaflet() %>% addTiles() %>% 
  addMarkers(lng = ~lon, lat = ~lat, label = ~yr)
```
