---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(dplyr)
library(formattable)
library(ggplot2)
library(lubridate)
library(DT)
library(tm)
library(wordcloud)
```

```{r data}
videos = read.csv("https://raw.githubusercontent.com/chzelada/ufm-dp-2022/main/FlexDashBoard/data/academatica_videos.csv", sep = ",")
metadata = read.csv("https://raw.githubusercontent.com/chzelada/ufm-dp-2022/main/FlexDashBoard/data/academatica_videos_metadata.csv", sep = ",")
stats = read.csv("https://raw.githubusercontent.com/chzelada/ufm-dp-2022/main/FlexDashBoard/data/academatica_video_stats.csv", sep = ",")
```

```{r kpis}
metricas = stats %>% summarise(tot_views = sum(viewCount), 
                               tot_likes = sum(likeCount), 
                               tot_dislikes = sum(dislikeCount), 
                               tot_favorite = sum(favoriteCount), 
                               tot_comments = sum(commentCount))
```

# Metrica {data-icon=fa-ruler}

##

### Reproducciones

```{r}
fviews = comma(metricas$tot_views,0)
valueBox(fviews, icon = "fa-eye", color = "success")
```

### Me Gustas

```{r}
flikes = comma(metricas$tot_likes,0)
valueBox(flikes, icon = "fa-thumbs-up", color = "warning")
```

### Comentarios

```{r}
fcomments = comma(metricas$tot_comments,0)
valueBox(fcomments, icon = "fa-comment", color = "danger")
```

##

###

```{r}
rlikes = metricas$tot_likes / (metricas$tot_likes+metricas$tot_dislikes)
rlikes = round(rlikes,2)*100
gauge(rlikes, min = 0, max = 100, symbol = '%', gaugeSectors(success = c(80,100),
   warning = c(40,79), danger = c(0,39)))
```

###

```{r}
rdislikes = metricas$tot_dislikes / (metricas$tot_likes+metricas$tot_dislikes)
rdislikes = round(rdislikes,2)*100
gauge(rdislikes, min = 0, max = 100, symbol = '%', gaugeSectors(danger = c(80,100),
   warning = c(40,79), success = c(0,39)))
```

##

###
```{r, fig.width=20}
videos %>% mutate(year = year(ymd_hms(contentDetails.videoPublishedAt)),
                  month = month(ymd_hms(contentDetails.videoPublishedAt)),
                  year = as.factor(year), month = as.factor(month)) %>%
    group_by(year, month) %>% summarise(uploaded_videos =n()) %>%
    ggplot(aes(x=month, y=uploaded_videos, fill = year)) + geom_col(position = 
    'dodge') + facet_grid(~year) + theme(axis.text.x = element_text(
      angle = 90, vjust = 0.5, hjust = 1
    ))
```

# Data {data-icon='fa-database'}

## {.tabset}

### data

```{r}
stats %>% left_join(metadata, by = c('id'='video_id')) %>% select(id, title,
    description, viewCount, likeCount) %>% datatable()
```

### wordcloud

```{r}
docs <- Corpus(VectorSource(metadata$title))
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "-")
docs <- tm_map(docs, toSpace, "\\(")
docs <- tm_map(docs, toSpace, "\\)")
docs <- tm_map(docs, toSpace, "\\|")

docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removeWords, stopwords("spanish"))

docs <- tm_map(docs, removeWords, c("video", 
                                    "problema",
                                    "ejemplo",
                                    "parte",
                                    "ejercicio",
                                    "ejercicios",
                                    "ejemplos")) 

docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, stripWhitespace)

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)

set.seed(1234)

wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=100, random.order=TRUE, rot.per=0.1, 
          colors=brewer.pal(8, "Dark2"))
```

